### ISSUE TITLE
The history prop is undefined

### ISSUE THREAD

**Issue by amirmohsen** [mjackson/react-history#18]
I was using version 0.13.3 of this package in my project. It was working fine, but I decided to upgrade to the  latest (0.18.2) and that broke it. When I first load the page, the history prop is undefined.

```js
<History basename={basename} keyLength={keyLength}>
	{({ history, action, location }) => {
		// history is undefined here
		return (
			<DispatchingRouter
				store={this.context.store || this.props.store}
				history={history}
				action={action}
				location={location}
				basename={basename}
				{...props}
			/>
		);
	}}
</History>
```

I've ended up reverting back to 0.13.3 for now.

**Comment by mjackson** [comment]
Ah, my apologies for the breakage. 0.x days, you know :) Now you just get the full `history` object in the callback, and you can pull `action` and `location` off of it.

```js
<History>
{history => {
  const { action, location } = history
  // ...
}}
</History>
```

**Comment by amirmohsen** [comment]
Thanks for the clarification.
